/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAddSourceRouteImport } from './routes/dashboard.add-source'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'
import { Route as DashboardDeliveriesRouteImport } from './routes/dashboard.deliveries'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardMapRouteImport } from './routes/dashboard.map'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSourcesRouteImport } from './routes/dashboard.sources'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardWarningsRouteImport } from './routes/dashboard.warnings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddSourceRoute = DashboardAddSourceRouteImport.update({
  id: '/add-source',
  path: '/add-source',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeliveriesRoute = DashboardDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSourcesRoute = DashboardSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWarningsRoute = DashboardWarningsRouteImport.update({
  id: '/warnings',
  path: '/warnings',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/add-source': typeof DashboardAddSourceRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/deliveries': typeof DashboardDeliveriesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sources': typeof DashboardSourcesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/warnings': typeof DashboardWarningsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/add-source': typeof DashboardAddSourceRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/deliveries': typeof DashboardDeliveriesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sources': typeof DashboardSourcesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/warnings': typeof DashboardWarningsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/add-source': typeof DashboardAddSourceRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/deliveries': typeof DashboardDeliveriesRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sources': typeof DashboardSourcesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/warnings': typeof DashboardWarningsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/add-source'
    | '/dashboard/alerts'
    | '/dashboard/deliveries'
    | '/dashboard/insights'
    | '/dashboard/map'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/sources'
    | '/dashboard/users'
    | '/dashboard/warnings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/add-source'
    | '/dashboard/alerts'
    | '/dashboard/deliveries'
    | '/dashboard/insights'
    | '/dashboard/map'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/sources'
    | '/dashboard/users'
    | '/dashboard/warnings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/add-source'
    | '/dashboard/alerts'
    | '/dashboard/deliveries'
    | '/dashboard/insights'
    | '/dashboard/map'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/sources'
    | '/dashboard/users'
    | '/dashboard/warnings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/add-source': {
      id: '/dashboard/add-source'
      path: '/add-source'
      fullPath: '/dashboard/add-source'
      preLoaderRoute: typeof DashboardAddSourceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deliveries': {
      id: '/dashboard/deliveries'
      path: '/deliveries'
      fullPath: '/dashboard/deliveries'
      preLoaderRoute: typeof DashboardDeliveriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sources': {
      id: '/dashboard/sources'
      path: '/sources'
      fullPath: '/dashboard/sources'
      preLoaderRoute: typeof DashboardSourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/warnings': {
      id: '/dashboard/warnings'
      path: '/warnings'
      fullPath: '/dashboard/warnings'
      preLoaderRoute: typeof DashboardWarningsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAddSourceRoute: typeof DashboardAddSourceRoute
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardDeliveriesRoute: typeof DashboardDeliveriesRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSourcesRoute: typeof DashboardSourcesRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWarningsRoute: typeof DashboardWarningsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAddSourceRoute: DashboardAddSourceRoute,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardDeliveriesRoute: DashboardDeliveriesRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSourcesRoute: DashboardSourcesRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWarningsRoute: DashboardWarningsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
